---
- include: create-spigot-lib-directories.yml
- include: copy-spigot-jar.yml
- include: update-minecraft-server-symlink.yml
- include_tasks: download-plugin.yml
  vars:
    plugin_filename: "Multiverse-Core-4.1.0.jar"
    plugin_url: "https://dl.dropboxusercontent.com/s/ide0vq0ys3ac0x3/Multiverse-Core-4.1.0.jar?dl=0"
    plugin_md5: "2a562ee4b5ed7676931ed8ca5af75cd1"
- include_tasks: download-plugin.yml
  vars:
    plugin_filename: "Multiverse-Portals-4.1.0.jar"
    plugin_url: "https://dl.dropboxusercontent.com/s/ufhdr5k6w2itdk9/Multiverse-Portals-4.1.0.jar?dl=0"
    plugin_md5: "fcf4ff85ae530056d212095fa2a8895f"
- include_tasks: download-plugin.yml
  vars:
    plugin_filename: "EssentialsX-2.17.1.0.jar"
    plugin_url: "https://dl.dropboxusercontent.com/s/9r8937xgyd1xtqa/EssentialsX-2.17.1.0.jar?dl=0"
    plugin_md5: "68114ed2533111cff6a532c83e7eeb8c"
- include_tasks: download-plugin.yml
  vars:
    plugin_filename: "LuckPerms-Bukkit-4.3.62.jar"
    plugin_url: "https://ci.lucko.me/job/LuckPerms/839/artifact/bukkit/build/libs/LuckPerms-Bukkit-4.3.62.jar"
    plugin_md5: "4a637699928da021c6f480844bee7f98"
- include_tasks: download-plugin.yml
  vars:
    plugin_filename: "worldedit-bukkit-7.1.0-beta-1.jar"
    plugin_url: "https://media.forgecdn.net/files/2844/696/worldedit-bukkit-7.1.0-beta-1.jar"
    plugin_md5: "68cfb73ff106a6f91e5bf2853329bea6"
- include_tasks: download-plugin.yml
  vars:
    plugin_filename: "perworldinventory-kt-2.2.1.jar"
    plugin_url: "https://github.com/EbonJaeger/perworldinventory-kt/releases/download/v2.2.1/perworldinventory-kt-2.2.1.jar"
    plugin_md5: "be6d8c3e35c37e7ab1d8e7f0e23292d5"

