---
- name: Install nfs-common package
  apt: name=nfs-common state=present
- name: Create minecraft NFS mount mount
  mount: name={{ minecraft_nfs_mount_point }} src={{ minecraft_nfs_home_fs }} fstype=nfs opts=auto,nofail,noatime,nolock,intr,tcp,actimeo=1800 state=mounted
- name: Create minecraft home directory as a symlink
  file: src={{ minecraft_nfs_mount_point }}/minecraft dest={{ minecraft_home }} state=link owner=minecraft group=minecraft
